[package]
name = "crust-bot"
version = "0.1.0"
authors = ["Marek Vrbka <marekvrbka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
procinfo = "0.4.2"